<?php

return [
    'GEOSERVER_WORKSPACE' => env('GEOSERVER_WORKSPACE'),
    'GEOSERVER' => env('GEOSERVER'),
    'GEOSERVER_URL' => env('GEOSERVER_URL'),
    'PGSQL_BIN_PATH' => env('PGSQL_BIN_PATH'),
    'AUTH_KEY' => env('AUTH_KEY'),
    'GEOSERVER_USERNAME' => env('GEOSERVER_USERNAME'),
    'GEOSERVER_AUTH_PROXY' => env('GEOSERVER_AUTH_PROXY'),
];
?>